name: CI

on:
  push:
  pull_request:

jobs:
  unix:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php-version == 'nightly' }}
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4', '8.5', 'nightly']
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Prepare build
        run: |
          phpize
          ./configure --enable-terminal

      - name: Build
        run: make -j"$(nproc)"

      - name: Test
        run: make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1

  windows:
    runs-on: windows-2022
    continue-on-error: ${{ matrix.php-version == 'master' }}
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4', '8.5', 'master']
        arch: ['x64']
        ts: ['nts', 'ts']
    steps:
      - uses: actions/checkout@v5

      - name: Build extension
        uses: php/php-windows-builder/extension@v1
        with:
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
